#!/usr/bin/python
from tcc3.command import TCC3Command, CliError

class Test(TCC3Command):

    descr = "Test values with data not selected for training"
    usage = "%prog --hostname NAME"

    def init_parser(self, parser):
        super(Test, self).init_parser(parser)
        parser.add_option("-H", "--hostname", type="string",
                help="The hostname whose information is from")

    def run(self):
        if self.opts.hostname is None:
            raise CliError, "you must supply the hostname"
        print self.tcc3.test(hostname=self.opts.hostname)

Test().main()

# vim:ts=4:sw=4:et
