#!/usr/bin/python
from tcc3.command import TCC3Command, CliError

class DumpDB(TCC3Command):

    descr = "Starts the main virtual machine scheduler"

    def run(self):
        self.tcc3.schedule()

DumpDB().main()

# vim:ts=4:sw=4:et
