#!/usr/bin/python
from tcc3.command import TCC3Command, CliError

class Train(TCC3Command):

    descr = "Train the learning method for a given host data"
    usage = "%prog --hostname NAME"

    def init_parser(self, parser):
        super(Train, self).init_parser(parser)
        parser.add_option("-H", "--hostname", type="string",
                help="The hostname whose information is from")

    def run(self):
        if self.opts.hostname is None:
            raise CliError, "you must supply the hostname"
        self.tcc3.train(hostname=self.opts.hostname)

Train().main()

# vim:ts=4:sw=4:et
